### ISSUE TITLE
Not HTTP but local images...

### ISSUE THREAD

**Issue by ttsoares** [andreyk1512/react-image-size#21]
Greetings...

I would like to do something like this:

`const [dimensions] = useImageSize("/public/imgs/picture.jpg");`

in a NextJS/React context.

**Comment by andreyk1512** [comment]
Hi
Thank you for the request.

I've just tested this issue and it works well for me.
Code:
<img width="970" alt="image" src="https://github.com/andreyk1512/react-image-size/assets/72908793/20ab66d2-b4fc-4d46-8929-c646ca40e197">
and the result is:
<img width="741" alt="image" src="https://github.com/andreyk1512/react-image-size/assets/72908793/dfaf7ec5-11cd-4066-981d-d40d1951bbf7">

Do you have some error? Or can you share the code where it doesn't work?

**Comment by ttsoares** [comment]
Thank you for this fast reply !
As I'm using this with NextJS I supposed that should use the full path to reach the img files:
as in '/public/imgs/photo.jpg'

But after your message, I tried like this: '/imgs/poho.jpg'  and then worked !
So the relative path is the correct, not the absolute.

Again: Thank you 8-)

**Comment by ttsoares** [comment]
It worked !!
I commented there about it...

Em sáb., 11 de nov. de 2023 às 16:12, Andrey Krupa ***@***.***>
escreveu:

**Comment by ttsoares** [comment]
Just a path issue...
