### ISSUE TITLE
ReferenceError: Image is not defined

### ISSUE THREAD

**Issue by davetapley** [andreyk1512/react-image-size#3]
On [next.js](https://nextjs.org/) this will throw:

```
error - unhandledRejection: ReferenceError: Image is not defined
```

Because `Image` in ⬇️  doesn't exist when doing [pre-rendering](https://nextjs.org/docs/basic-features/pages#pre-rendering).
https://github.com/andreyk1512/react-image-size/blob/5f9402d63d1920a71a8b8b80f43c73fc24e5748a/index.js#L10

---

As a workaround one can wrap with `typeof window !== "undefined" `, but might be worth doing that here to save confusion 😁

**Comment by andreyk1512** [comment]
I have added this "fuse" in 1.0.6 version. Thanks.
